"""Runtime contracts for Token Payments API and worker entrypoints."""

from importlib import import_module as _import_module

from .composition import (
    LIVE_RUNTIME_DRIVER_CONFIGURATION_INVALID,
    LIVE_RUNTIME_DEPENDENCY_MISSING,
    REQUIRED_LIVE_DEPENDENCIES,
    BlockchainClient,
    BlockchainReadinessProbe,
    EthAccountWalletSignatureClient,
    KafkaProducerClient,
    KafkaReadinessProbe,
    JsonRpcBlockchainClient,
    LazyKafkaProducerClient,
    LiveApiComposition,
    LiveApiFacades,
    LiveRuntimeConfig,
    LiveRuntimeDependencies,
    LiveRuntimeDriverConfigurationError,
    LiveRuntimeDependencyError,
    LiveWorkerDescriptor,
    PostgresReadinessProbe,
    PostgresSessionFactory,
    PsycopgPostgresSessionFactory,
    SystemClock,
    UuidIdGenerator,
    WalletSignatureClient,
    build_live_api_facades,
    build_live_api_router,
    build_live_readiness_probes,
    build_live_runtime_dependencies_from_env,
    describe_live_worker_registry,
    describe_live_runtime_dependencies,
    live_worker_registry,
)
from .config import RuntimeConfig
from .contracts import (
    Clock,
    CommandDispatchResult,
    CommandDispatchStatus,
    HealthState,
    HealthStatus,
    IdGenerator,
    JsonValue,
    RuntimeContainer,
    WorkerLoopOptions,
)
from .api_server import (
    LIVE_API_CONFIRMATION_REQUIRED,
    LIVE_API_SERVER_PLAN_CONTRACT,
    LiveApiServerPlan,
    LiveApiServerResult,
    build_live_asgi_application,
    build_live_http_router,
    build_live_system_router,
    describe_live_api_server_plan,
    run_live_api_server,
)
from .entrypoint import ContractRuntimeContainer, dispatch_runtime_command
from .observability import (
    AccessLogEvent,
    OperatorDashboardQuery,
    OperatorErrorSnapshot,
    OperatorObservabilityQueryPort,
    OperatorObservabilitySnapshot,
    OperatorOrderSnapshot,
    OperatorOutboxSnapshot,
    OperatorPage,
    OperatorPaymentSnapshot,
    OperatorSortDirection,
    OperatorWorkerSnapshot,
    PostgresOperatorObservabilityQuery,
    ReadinessProbe,
    ReadinessProbeResult,
    RuntimeReadinessStatus,
    actor_summary,
    evaluate_readiness,
)
from .session_transport import (
    AuthCookiePair,
    CookieSessionTransport,
    CookieSettings,
    SessionClaims,
    SessionKeyConfig,
    SessionKeyRing,
    SessionTokenSigner,
)
from .security import (
    CorsPolicy,
    CsrfTokenService,
    RequestGuard,
)
from .smoke import (
    AVAILABLE_SMOKE_SCENARIOS,
    SMOKE_CONTRACT,
    UNKNOWN_SMOKE_SCENARIO_ERROR,
    SmokeResult,
    SmokeScenarioResult,
    SmokeStatus,
    SmokeStep,
    UnknownSmokeScenario,
    describe_smoke_registry,
    run_smoke_scenario,
)
from .workers import (
    KafkaConsumerWorker,
    OutboxRelayWorker,
    PaymentReceiptPollingWorker,
    PaymentTimeoutCandidate,
    PaymentTimeoutWorker,
    WorkerBatchResult,
    WorkerRunSummary,
    WorkerRuntime,
)

__all__ = [
    "AVAILABLE_SMOKE_SCENARIOS",
    "AccessLogEvent",
    "AuthCookiePair",
    "BrowserPreviewHttpServer",
    "BrowserPreviewRequestHandler",
    "BlockchainClient",
    "BlockchainReadinessProbe",
    "Clock",
    "CommandDispatchResult",
    "CommandDispatchStatus",
    "ContractRuntimeContainer",
    "CookieSessionTransport",
    "CookieSettings",
    "CorsPolicy",
    "CsrfTokenService",
    "DEFAULT_BROWSER_PREVIEW_HOST",
    "DEFAULT_BROWSER_PREVIEW_PORT",
    "EthAccountWalletSignatureClient",
    "HealthState",
    "HealthStatus",
    "IdGenerator",
    "JsonValue",
    "KafkaConsumerWorker",
    "KafkaProducerClient",
    "KafkaReadinessProbe",
    "LIVE_API_CONFIRMATION_REQUIRED",
    "LIVE_API_SERVER_PLAN_CONTRACT",
    "LIVE_RUNTIME_DEPENDENCY_MISSING",
    "LIVE_RUNTIME_DRIVER_CONFIGURATION_INVALID",
    "JsonRpcBlockchainClient",
    "LazyKafkaProducerClient",
    "LiveApiComposition",
    "LiveApiFacades",
    "LiveApiServerPlan",
    "LiveApiServerResult",
    "LiveRuntimeConfig",
    "LiveRuntimeDependencies",
    "LiveRuntimeDriverConfigurationError",
    "LiveRuntimeDependencyError",
    "LiveWorkerDescriptor",
    "OperatorDashboardQuery",
    "OperatorErrorSnapshot",
    "OperatorObservabilityQueryPort",
    "OperatorObservabilitySnapshot",
    "OperatorOrderSnapshot",
    "OperatorOutboxSnapshot",
    "OperatorPage",
    "OperatorPaymentSnapshot",
    "OperatorSortDirection",
    "OperatorWorkerSnapshot",
    "OutboxRelayWorker",
    "PaymentReceiptPollingWorker",
    "PaymentTimeoutCandidate",
    "PaymentTimeoutWorker",
    "PostgresReadinessProbe",
    "PostgresSessionFactory",
    "PsycopgPostgresSessionFactory",
    "ReadinessProbe",
    "ReadinessProbeResult",
    "RequestGuard",
    "RuntimeConfig",
    "RuntimeContainer",
    "RuntimeReadinessStatus",
    "REQUIRED_LIVE_DEPENDENCIES",
    "SMOKE_CONTRACT",
    "SessionClaims",
    "SessionKeyConfig",
    "SessionKeyRing",
    "SessionTokenSigner",
    "SmokeResult",
    "SmokeScenarioResult",
    "SmokeStatus",
    "SmokeStep",
    "SystemClock",
    "PostgresOperatorObservabilityQuery",
    "UNKNOWN_SMOKE_SCENARIO_ERROR",
    "UnknownSmokeScenario",
    "UuidIdGenerator",
    "WalletSignatureClient",
    "WorkerBatchResult",
    "WorkerLoopOptions",
    "WorkerRunSummary",
    "WorkerRuntime",
    "build_live_asgi_application",
    "build_browser_preview_server",
    "build_live_http_router",
    "build_live_api_facades",
    "build_live_api_router",
    "build_live_readiness_probes",
    "build_live_runtime_dependencies_from_env",
    "build_live_system_router",
    "actor_summary",
    "describe_live_api_server_plan",
    "describe_live_worker_registry",
    "describe_live_runtime_dependencies",
    "describe_smoke_registry",
    "dispatch_runtime_command",
    "evaluate_readiness",
    "live_worker_registry",
    "render_browser_preview_document",
    "run_smoke_scenario",
    "run_live_api_server",
    "serve_browser_preview",
]

_BROWSER_PREVIEW_EXPORTS = frozenset(
    {
        "DEFAULT_BROWSER_PREVIEW_HOST",
        "DEFAULT_BROWSER_PREVIEW_PORT",
        "BrowserPreviewHttpServer",
        "BrowserPreviewRequestHandler",
        "build_browser_preview_server",
        "render_browser_preview_document",
        "serve_browser_preview",
    }
)


def __getattr__(name: str):
    if name in _BROWSER_PREVIEW_EXPORTS:
        value = getattr(_import_module("token_payments.runtime.browser_preview"), name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
