#!/bin/bash

set -e

set -u

# 아직 만들 데이터베이스가 없음
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $POSTGRES_USER_BE_USER WITH PASSWORD '${POSTGRES_USER_BE_PASSWORD}';
	CREATE DATABASE $POSTGRES_USER_BE_DB;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_USER_BE_DB TO $POSTGRES_USER_BE_USER;

	CREATE USER $POSTGRES_GAME_BE_USER WITH PASSWORD '${POSTGRES_GAME_BE_PASSWORD}';
	CREATE DATABASE $POSTGRES_GAME_BE_DB;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_GAME_BE_DB TO $POSTGRES_GAME_BE_USER;

	\connect $POSTGRES_USER_BE_DB;
	CREATE SCHEMA $POSTGRES_USER_BE_SCHEMA AUTHORIZATION $POSTGRES_USER_BE_USER;
	ALTER ROLE $POSTGRES_USER_BE_USER SET client_encoding TO 'utf8';
	ALTER ROLE $POSTGRES_USER_BE_USER SET default_transaction_isolation TO 'read committed';
	ALTER ROLE $POSTGRES_USER_BE_USER SET timezone TO 'UTC';

	\connect $POSTGRES_GAME_BE_DB;
	CREATE SCHEMA $POSTGRES_GAME_BE_SCHEMA AUTHORIZATION $POSTGRES_GAME_BE_USER;
	ALTER ROLE $POSTGRES_GAME_BE_USER SET client_encoding TO 'utf8';
	ALTER ROLE $POSTGRES_GAME_BE_USER SET default_transaction_isolation TO 'read committed';
	ALTER ROLE $POSTGRES_GAME_BE_USER SET timezone TO 'UTC';
EOSQL
