"""Authentication application layer."""

from .ports import (
    AuthEventPublisher,
    AuthRbacRepository,
    AuthSessionRepository,
    AuthUseCase,
    CurrentUserQuery,
    GetCurrentUserProfileQuery,
    GetUserProfileQuery,
    LinkWalletCommand,
    ListWalletsQuery,
    LoginChallengeRepository,
    LoginChallengeResult,
    LoginResult,
    LoginWithMetaMaskCommand,
    LogoutCommand,
    RefreshSessionCommand,
    RequestLoginChallengeCommand,
    RequestWalletLinkChallengeCommand,
    RevokeWalletCommand,
    SetPrimaryWalletCommand,
    TokenIssuer,
    UpdateUserProfileCommand,
    UserProfileRepository,
    UserRepository,
    UserWalletRepository,
    WalletLinkChallengeResult,
    WalletResult,
    WalletSignatureVerificationFailure,
    WalletSignatureVerificationResult,
    WalletSignatureVerifier,
    WalletsResult,
)
from .authorization import AuthorizationPolicy, AuthorizationRepository, ResourceRef
from .merchant_membership import (
    MERCHANT_ASSIGNABLE_ROLE_IDS,
    OWNER_ROLE_ID,
    MerchantActor,
    MerchantMembershipRepository,
    MerchantMembershipResult,
    MerchantMembershipService,
)
from .service import AuthApplicationError, AuthApplicationService, AuthErrorCode
from .siwe import SIWE_VERSION, SiweMessage, build_siwe_message, parse_siwe_message

__all__ = [
    "AuthApplicationError",
    "AuthApplicationService",
    "AuthErrorCode",
    "AuthEventPublisher",
    "AuthRbacRepository",
    "AuthSessionRepository",
    "AuthUseCase",
    "AuthorizationPolicy",
    "AuthorizationRepository",
    "CurrentUserQuery",
    "GetCurrentUserProfileQuery",
    "GetUserProfileQuery",
    "LinkWalletCommand",
    "ListWalletsQuery",
    "LoginChallengeRepository",
    "LoginChallengeResult",
    "LoginResult",
    "LoginWithMetaMaskCommand",
    "LogoutCommand",
    "MERCHANT_ASSIGNABLE_ROLE_IDS",
    "OWNER_ROLE_ID",
    "MerchantActor",
    "MerchantMembershipRepository",
    "MerchantMembershipResult",
    "MerchantMembershipService",
    "RefreshSessionCommand",
    "RequestLoginChallengeCommand",
    "RequestWalletLinkChallengeCommand",
    "RevokeWalletCommand",
    "ResourceRef",
    "SIWE_VERSION",
    "SetPrimaryWalletCommand",
    "SiweMessage",
    "TokenIssuer",
    "UpdateUserProfileCommand",
    "UserProfileRepository",
    "UserRepository",
    "UserWalletRepository",
    "WalletLinkChallengeResult",
    "WalletResult",
    "WalletSignatureVerificationFailure",
    "WalletSignatureVerificationResult",
    "WalletSignatureVerifier",
    "WalletsResult",
    "build_siwe_message",
    "parse_siwe_message",
]
